name: .NET

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build_and_test:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 7.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore --configuration Release
    - name: Run Tests
      run: |
        for i in {1..5}; do
          echo "Running test #$i"
          dotnet run --project TransportationProblemSolver/TransportationProblemSolver.csproj --configuration Release --no-build -- data/in$i.txt data/out$i.txt
          diff data/out$i.txt expected/out$i.txt
        done
